futbol_equipo:
    resource: "@FutbolBundle/Resources/config/routing/equipo.yml"
    prefix:   /equipo
futbol_entrenador:
    resource: "@FutbolBundle/Resources/config/routing/entrenador.yml"
    prefix:   /entrenador

futbol_homepage:
    path:     /
    defaults: { _controller: FutbolBundle:Default:index }
